language: "node_js"
node_js:
  - "0.10"
  - "0.8"
#  - "0.6"
  - "0.4"

before_install:
  - "npm install istanbul -g"
  - "npm install coveralls -g"

after_success:
  - "cat reports/coverage/lcov.info | coveralls"